import NavBar from "./components/NavBar";
import AuthContext from "./context/AuthContext";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <main className="bg-gray-100 min-h-screen w-screen">
                    <AuthContext>
                        <main className="max-w-screen-2xl m-auto bg-gray-100">
                            <NavBar></NavBar>
                            {children}
                        </main>
                    </AuthContext>
                </main>
            </body>
        </html>
    );
}
